name: "McKenna's Eye"
favicon: null
layout_spectrum: 0.99876
typography_spectrum: 0.04332
title: "McKenna's Eye"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafbed'
    - '#f5907c'
    - '#7bcad1'
    - '#929292'
    - '#b7b7b7'
  brandStrength: 0.3125
  lightness: 0.7264011388178915
  saturation: 0
  rhythmicContrast: 0
purpose: []
